FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/rs92
RUN gcc rs92gps.c -lm -o rs92gps

WORKDIR /repo/rs41
RUN gcc rs41.c -lm -o rs41

WORKDIR /repo/meisei
RUN gcc meisei_rs.c -lm -o meisei_rs
FROM ubuntu:20.04 as package
COPY --from=builder /repo/rs41/rs41 /
